### PR TITLE
FIX: 'process' has been deprecated. CORE: empover Gutenberg editor to…

### PR DESCRIPTION
**Pull request by Koli14**
… style

### CODE REVIEW

**Review by luisherranz — CHANGES_REQUESTED** [review]
Thanks @Koli14!

Could you please change `node` to `({ node })` as well?

```js
processor: ({ node }) => {
```

```js
test: ({ node }) => {
```

By the way, why do you need to do this?

```js
const classNames = node.props.className; //save it for later
node.props.className = classNames; //Add classNames, to empover Gutenberg editor
```

It doesn't seem to do anything to me.

**Comment by Koli14** [comment]
Without `classNames` you loose the `class`-es added by Gutenberg (e.g.:.`has-text-align-center .is-style-large .has-text-color .has-luminous-vivid-orange-color .has-background`).

**Comment by luisherranz** [comment]
Ok, thanks @Koli14. Seems fine to me.

@segunadebayo what do you think? Can you release a new version with this?

**Review by luisherranz — CHANGES_REQUESTED** [review]
@Koli14 I finally understand why you need that.

I think it would be much better to preserve all the attributes, like this:

```js
function makeProcessor(tag, options) {
  return {
    name: tag,
    test: ({ node }) => node.component === tag,
    processor: ({ node }) => {
      node.component = options.component || node.tag;
      node.props = { ...options.props({ node }), ...node.props };
      return node;
    },
    priority: 20
  };
}
```

I cannot push to your branch, but you can see my code here: https://github.com/luisherranz/frontity-chakra-ui-theme/blob/12-new-processors-attributes/packages/frontity-chakra-theme/src/components/styles/processors.js

**Comment by Koli14** [comment]
I agree @luisherranz, it's much better!

**Review by luisherranz — APPROVED** [review]
Awesome, thanks @Koli14! :)

**Pull request merged**
